#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"



source ~/.bash_profile

# Git aliases

alias code="code-insiders"
alias c="code"
alias gs="git status"
alias status="git status"
alias gsa="~/dotfiles/clustergit/clustergit --recursive -d ."
alias gd="git diff"
alias ga="git add -A"
alias add="git add -A"
alias gc="git commit"
alias commit="git commit"
alias gca="git commit --amend"
alias gp="git push"
alias push="git push"
alias pull="git pull"
gpa() { git add -A && git commit -m  "$*" && git push; }


# General aliases

alias l='ls -lahF'
alias copy='fc -ln -1 | sed "1s/^[[:space:]]*//" | awk 1 ORS="" | pbcopy '
alias mkdir="mkdir -p"
alias mv="mv -iv"
alias cp="cp -iv"
alias rd="rm -rfv"
alias hd="head"
alias tl="tail"
alias zapem="gs | grep DS_Store | awk '{print $2}' | xargs git checkout"
alias yarn-work="yarn config delete registry -g"
alias yarn-public="yarn config set registry "https://registry.yarnpkg.com" -g"
function kp { ps -ef | grep "$@" | awk '{print $2}' | xargs sudo kill }
function hide(){
    defaults write com.apple.finder AppleShowAllFiles -bool NO
    killall Finder
}
function show(){
    defaults write com.apple.finder AppleShowAllFiles -bool YES
    killall Finder
}

# Docker aliases
alias dcu='docker-compose up -d'
alias dcps='docker-compose ps'
alias bedrock="osascript ~/Desktop/scripts/bedrock.scpt"
